name       : mate-polkit
version    : 1.27.0
release    : 17
source     :
    - https://github.com/mate-desktop/mate-polkit/releases/download/v1.27.0/mate-polkit-1.27.0.tar.xz : 39640971872d9b0a4db331bc31e1097a9929d1360fda54bfe46efa0ae27b5676
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    : MATE PolicyKit Agent
component  : desktop.mate
description: |
    This package provides an Authentication Agent for PolicyKit that integrates well with the MATE desktop environment
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - accountsservice
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-libayatana-appindicator.patch
    %configure --disable-static \
        --enable-accountsservice \
        --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
