name       : mate-polkit
version    : 1.18.2
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-polkit-1.18.2.tar.xz : 6dc987edfa6239ded5edc8a472a19a77839348519cf24cd968019420f9a1bd06
license    : LGPL-2.0
summary    : MATE PolicyKit Agent
component  : desktop.mate
description: |
    MATE PolicyKit Agent
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - accountsservice
setup      : |
    %configure --disable-static \
               --enable-accountsservice \
               --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
