name       : mate-polkit
version    : 1.16.0
release    : 5
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-polkit-1.16.0.tar.xz : e0aba1f4be2fef30a74509aef92c5773ee17c2279f158a7295415f700713457c
license    : LGPL-2.0
summary    : MATE PolicyKit Agent
component  : desktop.mate
description: |
    MATE PolicyKit Agent
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - accountsservice
setup      : |
    %configure --disable-static \
               --enable-accountsservice \
               --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
