name       : mate-polkit
version    : 1.22.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-polkit/archive/v1.22.0.tar.gz : 3150362383c1e9330413d336eefc2c93e87059f5677e4dc660d48f3ff4a44c19
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    : MATE PolicyKit Agent
component  : desktop.mate
description: |
    This package provides an Authentication Agent for PolicyKit that integrates well with the MATE desktop environment
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
    - mate-common
rundeps    :
    - accountsservice
setup      : |
    %autogen --disable-maintainer-mode \
        --disable-static \
        --enable-accountsservice \
        --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
