name       : mate-polkit
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-polkit-1.20.0.tar.xz : 242988d0033f878b967dea5ad380cc7cb49910b9b2ea33e95061bf3062cd8101
license    : LGPL-2.0
summary    : MATE PolicyKit Agent
component  : desktop.mate
description: |
    MATE PolicyKit Agent
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - accountsservice
setup      : |
    %configure --disable-static \
               --enable-accountsservice \
               --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
