name       : mate-polkit
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-polkit-1.16.0.tar.xz : e0aba1f4be2fef30a74509aef92c5773ee17c2279f158a7295415f700713457c
license    : LGPL-2.0
summary    : MATE PolicyKit
component  : desktop.mate
description: |
    MATE PolicyKit
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
