name       : mate-polkit
version    : 1.14.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-polkit-1.14.0.tar.xz : 929d5710d6284f924dc65824b75e9da23b5809c50033da18b6b4b79e0f599ddd
license    : LGPL-2.0
summary    : MATE PolicyKit
component  : desktop.mate
description: |
    MATE PolicyKit
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
